// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.33.2
// source: topology.proto

package topology

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Physical topology for a single host (subset of PhysicalSystemDescriptor).
type HostPhysicalTopology struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// All ASICs discovered on this host.
	Asics []*AsicInfo `protobuf:"bytes,1,rep,name=asics,proto3" json:"asics,omitempty"`
	// Intra-host ethernet connections (between ASICs on this host).
	LocalConnections []*LocalEthConnection `protobuf:"bytes,2,rep,name=local_connections,json=localConnections,proto3" json:"local_connections,omitempty"`
	// Exit node connections (to ASICs on other hosts).
	ExitNodes []*ExitNodeInfo `protobuf:"bytes,3,rep,name=exit_nodes,json=exitNodes,proto3" json:"exit_nodes,omitempty"`
}

func (x *HostPhysicalTopology) Reset() {
	*x = HostPhysicalTopology{}
	if protoimpl.UnsafeEnabled {
		mi := &file_topology_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostPhysicalTopology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostPhysicalTopology) ProtoMessage() {}

func (x *HostPhysicalTopology) ProtoReflect() protoreflect.Message {
	mi := &file_topology_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostPhysicalTopology.ProtoReflect.Descriptor instead.
func (*HostPhysicalTopology) Descriptor() ([]byte, []int) {
	return file_topology_proto_rawDescGZIP(), []int{0}
}

func (x *HostPhysicalTopology) GetAsics() []*AsicInfo {
	if x != nil {
		return x.Asics
	}
	return nil
}

func (x *HostPhysicalTopology) GetLocalConnections() []*LocalEthConnection {
	if x != nil {
		return x.LocalConnections
	}
	return nil
}

func (x *HostPhysicalTopology) GetExitNodes() []*ExitNodeInfo {
	if x != nil {
		return x.ExitNodes
	}
	return nil
}

// Information about a single ASIC.
type AsicInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UniqueId       uint64 `protobuf:"varint,1,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`                     // Globally unique ASIC ID
	BoardType      uint32 `protobuf:"varint,2,opt,name=board_type,json=boardType,proto3" json:"board_type,omitempty"`                  // tt::BoardType enum value
	TrayId         uint32 `protobuf:"varint,3,opt,name=tray_id,json=trayId,proto3" json:"tray_id,omitempty"`                           // Physical tray identifier
	AsicLocation   uint32 `protobuf:"varint,4,opt,name=asic_location,json=asicLocation,proto3" json:"asic_location,omitempty"`         // Position within tray/board
	ChipArch       string `protobuf:"bytes,5,opt,name=chip_arch,json=chipArch,proto3" json:"chip_arch,omitempty"`                      // Architecture string (e.g., "wormhole_b0")
	MemoryBytes    uint64 `protobuf:"varint,6,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`            // Total DRAM in bytes
	PciAddress     string `protobuf:"bytes,7,opt,name=pci_address,json=pciAddress,proto3" json:"pci_address,omitempty"`                // PCI BDF address (only set for MMIO capable chips)
	ChipId         uint32 `protobuf:"varint,8,opt,name=chip_id,json=chipId,proto3" json:"chip_id,omitempty"`                           // Logical chip id within the host
	IsMmioCapable  bool   `protobuf:"varint,9,opt,name=is_mmio_capable,json=isMmioCapable,proto3" json:"is_mmio_capable,omitempty"`    // Is the chip capable of addressing host memory
	DeviceNodeId   uint32 `protobuf:"varint,10,opt,name=device_node_id,json=deviceNodeId,proto3" json:"device_node_id,omitempty"`      // Device node identifier (the N in /dev/tenstorrent/N)
	DeviceNodePath string `protobuf:"bytes,11,opt,name=device_node_path,json=deviceNodePath,proto3" json:"device_node_path,omitempty"` // Device node path (e.g. /dev/tenstorrent/1)
}

func (x *AsicInfo) Reset() {
	*x = AsicInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_topology_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AsicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsicInfo) ProtoMessage() {}

func (x *AsicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_topology_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsicInfo.ProtoReflect.Descriptor instead.
func (*AsicInfo) Descriptor() ([]byte, []int) {
	return file_topology_proto_rawDescGZIP(), []int{1}
}

func (x *AsicInfo) GetUniqueId() uint64 {
	if x != nil {
		return x.UniqueId
	}
	return 0
}

func (x *AsicInfo) GetBoardType() uint32 {
	if x != nil {
		return x.BoardType
	}
	return 0
}

func (x *AsicInfo) GetTrayId() uint32 {
	if x != nil {
		return x.TrayId
	}
	return 0
}

func (x *AsicInfo) GetAsicLocation() uint32 {
	if x != nil {
		return x.AsicLocation
	}
	return 0
}

func (x *AsicInfo) GetChipArch() string {
	if x != nil {
		return x.ChipArch
	}
	return ""
}

func (x *AsicInfo) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *AsicInfo) GetPciAddress() string {
	if x != nil {
		return x.PciAddress
	}
	return ""
}

func (x *AsicInfo) GetChipId() uint32 {
	if x != nil {
		return x.ChipId
	}
	return 0
}

func (x *AsicInfo) GetIsMmioCapable() bool {
	if x != nil {
		return x.IsMmioCapable
	}
	return false
}

func (x *AsicInfo) GetDeviceNodeId() uint32 {
	if x != nil {
		return x.DeviceNodeId
	}
	return 0
}

func (x *AsicInfo) GetDeviceNodePath() string {
	if x != nil {
		return x.DeviceNodePath
	}
	return ""
}

// Local ethernet connection (between ASICs on same host).
type LocalEthConnection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcAsicId  uint64 `protobuf:"varint,1,opt,name=src_asic_id,json=srcAsicId,proto3" json:"src_asic_id,omitempty"`
	SrcChannel uint32 `protobuf:"varint,2,opt,name=src_channel,json=srcChannel,proto3" json:"src_channel,omitempty"`
	DstAsicId  uint64 `protobuf:"varint,3,opt,name=dst_asic_id,json=dstAsicId,proto3" json:"dst_asic_id,omitempty"`
	DstChannel uint32 `protobuf:"varint,4,opt,name=dst_channel,json=dstChannel,proto3" json:"dst_channel,omitempty"`
}

func (x *LocalEthConnection) Reset() {
	*x = LocalEthConnection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_topology_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalEthConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalEthConnection) ProtoMessage() {}

func (x *LocalEthConnection) ProtoReflect() protoreflect.Message {
	mi := &file_topology_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalEthConnection.ProtoReflect.Descriptor instead.
func (*LocalEthConnection) Descriptor() ([]byte, []int) {
	return file_topology_proto_rawDescGZIP(), []int{2}
}

func (x *LocalEthConnection) GetSrcAsicId() uint64 {
	if x != nil {
		return x.SrcAsicId
	}
	return 0
}

func (x *LocalEthConnection) GetSrcChannel() uint32 {
	if x != nil {
		return x.SrcChannel
	}
	return 0
}

func (x *LocalEthConnection) GetDstAsicId() uint64 {
	if x != nil {
		return x.DstAsicId
	}
	return 0
}

func (x *LocalEthConnection) GetDstChannel() uint32 {
	if x != nil {
		return x.DstChannel
	}
	return 0
}

// Exit node connection (to ASIC on remote host).
type ExitNodeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocalAsicId   uint64 `protobuf:"varint,1,opt,name=local_asic_id,json=localAsicId,proto3" json:"local_asic_id,omitempty"`     // ASIC on this host
	LocalChannel  uint32 `protobuf:"varint,2,opt,name=local_channel,json=localChannel,proto3" json:"local_channel,omitempty"`    // Ethernet channel on local ASIC
	RemoteAsicId  uint64 `protobuf:"varint,3,opt,name=remote_asic_id,json=remoteAsicId,proto3" json:"remote_asic_id,omitempty"`  // ASIC unique ID on remote host
	RemoteChannel uint32 `protobuf:"varint,4,opt,name=remote_channel,json=remoteChannel,proto3" json:"remote_channel,omitempty"` // Ethernet channel on remote ASIC
}

func (x *ExitNodeInfo) Reset() {
	*x = ExitNodeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_topology_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExitNodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitNodeInfo) ProtoMessage() {}

func (x *ExitNodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_topology_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitNodeInfo.ProtoReflect.Descriptor instead.
func (*ExitNodeInfo) Descriptor() ([]byte, []int) {
	return file_topology_proto_rawDescGZIP(), []int{3}
}

func (x *ExitNodeInfo) GetLocalAsicId() uint64 {
	if x != nil {
		return x.LocalAsicId
	}
	return 0
}

func (x *ExitNodeInfo) GetLocalChannel() uint32 {
	if x != nil {
		return x.LocalChannel
	}
	return 0
}

func (x *ExitNodeInfo) GetRemoteAsicId() uint64 {
	if x != nil {
		return x.RemoteAsicId
	}
	return 0
}

func (x *ExitNodeInfo) GetRemoteChannel() uint32 {
	if x != nil {
		return x.RemoteChannel
	}
	return 0
}

var File_topology_proto protoreflect.FileDescriptor

var file_topology_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x74, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x16, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e,
	0x74, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x22, 0xec, 0x01, 0x0a, 0x14, 0x48, 0x6f, 0x73,
	0x74, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67,
	0x79, 0x12, 0x36, 0x0a, 0x05, 0x61, 0x73, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x2e, 0x74, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x2e, 0x41, 0x73, 0x69, 0x63, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x05, 0x61, 0x73, 0x69, 0x63, 0x73, 0x12, 0x57, 0x0a, 0x11, 0x6c, 0x6f, 0x63,
	0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x2e, 0x74, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x2e, 0x4c, 0x6f,
	0x63, 0x61, 0x6c, 0x45, 0x74, 0x68, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x10, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x43, 0x0a, 0x0a, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x74, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x2e,
	0x45, 0x78, 0x69, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x65, 0x78,
	0x69, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0xf6, 0x02, 0x0a, 0x08, 0x41, 0x73, 0x69, 0x63,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x74, 0x72, 0x61, 0x79, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x73, 0x69,
	0x63, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0c, 0x61, 0x73, 0x69, 0x63, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b,
	0x0a, 0x09, 0x63, 0x68, 0x69, 0x70, 0x5f, 0x61, 0x72, 0x63, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x68, 0x69, 0x70, 0x41, 0x72, 0x63, 0x68, 0x12, 0x21, 0x0a, 0x0c, 0x6d,
	0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0b, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x1f,
	0x0a, 0x0b, 0x70, 0x63, 0x69, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x63, 0x69, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x17, 0x0a, 0x07, 0x63, 0x68, 0x69, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x63, 0x68, 0x69, 0x70, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x69, 0x73, 0x5f, 0x6d,
	0x6d, 0x69, 0x6f, 0x5f, 0x63, 0x61, 0x70, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0d, 0x69, 0x73, 0x4d, 0x6d, 0x69, 0x6f, 0x43, 0x61, 0x70, 0x61, 0x62, 0x6c, 0x65,
	0x12, 0x24, 0x0a, 0x0e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x61, 0x74, 0x68,
	0x22, 0x96, 0x01, 0x0a, 0x12, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x45, 0x74, 0x68, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0b, 0x73, 0x72, 0x63, 0x5f, 0x61,
	0x73, 0x69, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x72,
	0x63, 0x41, 0x73, 0x69, 0x63, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x72, 0x63, 0x5f, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x72,
	0x63, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1e, 0x0a, 0x0b, 0x64, 0x73, 0x74, 0x5f,
	0x61, 0x73, 0x69, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x64,
	0x73, 0x74, 0x41, 0x73, 0x69, 0x63, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x73, 0x74, 0x5f,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x64,
	0x73, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x22, 0xa4, 0x01, 0x0a, 0x0c, 0x45, 0x78,
	0x69, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x22, 0x0a, 0x0d, 0x6c, 0x6f,
	0x63, 0x61, 0x6c, 0x5f, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x41, 0x73, 0x69, 0x63, 0x49, 0x64, 0x12, 0x23,
	0x0a, 0x0d, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x12, 0x24, 0x0a, 0x0e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x61, 0x73,
	0x69, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x72, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x41, 0x73, 0x69, 0x63, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0d, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_topology_proto_rawDescOnce sync.Once
	file_topology_proto_rawDescData = file_topology_proto_rawDesc
)

func file_topology_proto_rawDescGZIP() []byte {
	file_topology_proto_rawDescOnce.Do(func() {
		file_topology_proto_rawDescData = protoimpl.X.CompressGZIP(file_topology_proto_rawDescData)
	})
	return file_topology_proto_rawDescData
}

var file_topology_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_topology_proto_goTypes = []interface{}{
	(*HostPhysicalTopology)(nil), // 0: fabricmanager.topology.HostPhysicalTopology
	(*AsicInfo)(nil),             // 1: fabricmanager.topology.AsicInfo
	(*LocalEthConnection)(nil),   // 2: fabricmanager.topology.LocalEthConnection
	(*ExitNodeInfo)(nil),         // 3: fabricmanager.topology.ExitNodeInfo
}
var file_topology_proto_depIdxs = []int32{
	1, // 0: fabricmanager.topology.HostPhysicalTopology.asics:type_name -> fabricmanager.topology.AsicInfo
	2, // 1: fabricmanager.topology.HostPhysicalTopology.local_connections:type_name -> fabricmanager.topology.LocalEthConnection
	3, // 2: fabricmanager.topology.HostPhysicalTopology.exit_nodes:type_name -> fabricmanager.topology.ExitNodeInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_topology_proto_init() }
func file_topology_proto_init() {
	if File_topology_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_topology_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostPhysicalTopology); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_topology_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AsicInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_topology_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalEthConnection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_topology_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExitNodeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_topology_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_topology_proto_goTypes,
		DependencyIndexes: file_topology_proto_depIdxs,
		MessageInfos:      file_topology_proto_msgTypes,
	}.Build()
	File_topology_proto = out.File
	file_topology_proto_rawDesc = nil
	file_topology_proto_goTypes = nil
	file_topology_proto_depIdxs = nil
}
