// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: topology.proto

package topology

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Physical topology for a single host (subset of PhysicalSystemDescriptor).
type HostPhysicalTopology struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All ASICs discovered on this host.
	Asics []*AsicInfo `protobuf:"bytes,1,rep,name=asics,proto3" json:"asics,omitempty"`
	// Intra-host ethernet connections (between ASICs on this host).
	LocalConnections []*LocalEthConnection `protobuf:"bytes,2,rep,name=local_connections,json=localConnections,proto3" json:"local_connections,omitempty"`
	// Exit node connections (to ASICs on other hosts).
	ExitNodes     []*ExitNodeInfo `protobuf:"bytes,3,rep,name=exit_nodes,json=exitNodes,proto3" json:"exit_nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostPhysicalTopology) Reset() {
	*x = HostPhysicalTopology{}
	mi := &file_topology_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostPhysicalTopology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostPhysicalTopology) ProtoMessage() {}

func (x *HostPhysicalTopology) ProtoReflect() protoreflect.Message {
	mi := &file_topology_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostPhysicalTopology.ProtoReflect.Descriptor instead.
func (*HostPhysicalTopology) Descriptor() ([]byte, []int) {
	return file_topology_proto_rawDescGZIP(), []int{0}
}

func (x *HostPhysicalTopology) GetAsics() []*AsicInfo {
	if x != nil {
		return x.Asics
	}
	return nil
}

func (x *HostPhysicalTopology) GetLocalConnections() []*LocalEthConnection {
	if x != nil {
		return x.LocalConnections
	}
	return nil
}

func (x *HostPhysicalTopology) GetExitNodes() []*ExitNodeInfo {
	if x != nil {
		return x.ExitNodes
	}
	return nil
}

// Information about a single ASIC.
type AsicInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UniqueId      uint64                 `protobuf:"varint,1,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`                  // Globally unique ASIC ID
	BoardType     uint32                 `protobuf:"varint,2,opt,name=board_type,json=boardType,proto3" json:"board_type,omitempty"`               // tt::BoardType enum value
	TrayId        uint32                 `protobuf:"varint,3,opt,name=tray_id,json=trayId,proto3" json:"tray_id,omitempty"`                        // Physical tray identifier
	AsicLocation  uint32                 `protobuf:"varint,4,opt,name=asic_location,json=asicLocation,proto3" json:"asic_location,omitempty"`      // Position within tray/board
	ChipArch      string                 `protobuf:"bytes,5,opt,name=chip_arch,json=chipArch,proto3" json:"chip_arch,omitempty"`                   // Architecture string (e.g., "wormhole_b0")
	MemoryBytes   uint64                 `protobuf:"varint,6,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`         // Total DRAM in bytes
	PciAddress    string                 `protobuf:"bytes,7,opt,name=pci_address,json=pciAddress,proto3" json:"pci_address,omitempty"`             // PCI BDF address (only set for MMIO capable chips)
	ChipId        uint32                 `protobuf:"varint,8,opt,name=chip_id,json=chipId,proto3" json:"chip_id,omitempty"`                        // Logical chip id within the host
	IsMmioCapable bool                   `protobuf:"varint,9,opt,name=is_mmio_capable,json=isMmioCapable,proto3" json:"is_mmio_capable,omitempty"` // Is the chip capable of addressing host memory
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsicInfo) Reset() {
	*x = AsicInfo{}
	mi := &file_topology_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsicInfo) ProtoMessage() {}

func (x *AsicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_topology_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsicInfo.ProtoReflect.Descriptor instead.
func (*AsicInfo) Descriptor() ([]byte, []int) {
	return file_topology_proto_rawDescGZIP(), []int{1}
}

func (x *AsicInfo) GetUniqueId() uint64 {
	if x != nil {
		return x.UniqueId
	}
	return 0
}

func (x *AsicInfo) GetBoardType() uint32 {
	if x != nil {
		return x.BoardType
	}
	return 0
}

func (x *AsicInfo) GetTrayId() uint32 {
	if x != nil {
		return x.TrayId
	}
	return 0
}

func (x *AsicInfo) GetAsicLocation() uint32 {
	if x != nil {
		return x.AsicLocation
	}
	return 0
}

func (x *AsicInfo) GetChipArch() string {
	if x != nil {
		return x.ChipArch
	}
	return ""
}

func (x *AsicInfo) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *AsicInfo) GetPciAddress() string {
	if x != nil {
		return x.PciAddress
	}
	return ""
}

func (x *AsicInfo) GetChipId() uint32 {
	if x != nil {
		return x.ChipId
	}
	return 0
}

func (x *AsicInfo) GetIsMmioCapable() bool {
	if x != nil {
		return x.IsMmioCapable
	}
	return false
}

// Local ethernet connection (between ASICs on same host).
type LocalEthConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcAsicId     uint64                 `protobuf:"varint,1,opt,name=src_asic_id,json=srcAsicId,proto3" json:"src_asic_id,omitempty"`
	SrcChannel    uint32                 `protobuf:"varint,2,opt,name=src_channel,json=srcChannel,proto3" json:"src_channel,omitempty"`
	DstAsicId     uint64                 `protobuf:"varint,3,opt,name=dst_asic_id,json=dstAsicId,proto3" json:"dst_asic_id,omitempty"`
	DstChannel    uint32                 `protobuf:"varint,4,opt,name=dst_channel,json=dstChannel,proto3" json:"dst_channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalEthConnection) Reset() {
	*x = LocalEthConnection{}
	mi := &file_topology_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalEthConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalEthConnection) ProtoMessage() {}

func (x *LocalEthConnection) ProtoReflect() protoreflect.Message {
	mi := &file_topology_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalEthConnection.ProtoReflect.Descriptor instead.
func (*LocalEthConnection) Descriptor() ([]byte, []int) {
	return file_topology_proto_rawDescGZIP(), []int{2}
}

func (x *LocalEthConnection) GetSrcAsicId() uint64 {
	if x != nil {
		return x.SrcAsicId
	}
	return 0
}

func (x *LocalEthConnection) GetSrcChannel() uint32 {
	if x != nil {
		return x.SrcChannel
	}
	return 0
}

func (x *LocalEthConnection) GetDstAsicId() uint64 {
	if x != nil {
		return x.DstAsicId
	}
	return 0
}

func (x *LocalEthConnection) GetDstChannel() uint32 {
	if x != nil {
		return x.DstChannel
	}
	return 0
}

// Exit node connection (to ASIC on remote host).
type ExitNodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocalAsicId   uint64                 `protobuf:"varint,1,opt,name=local_asic_id,json=localAsicId,proto3" json:"local_asic_id,omitempty"`     // ASIC on this host
	LocalChannel  uint32                 `protobuf:"varint,2,opt,name=local_channel,json=localChannel,proto3" json:"local_channel,omitempty"`    // Ethernet channel on local ASIC
	RemoteAsicId  uint64                 `protobuf:"varint,3,opt,name=remote_asic_id,json=remoteAsicId,proto3" json:"remote_asic_id,omitempty"`  // ASIC unique ID on remote host
	RemoteChannel uint32                 `protobuf:"varint,4,opt,name=remote_channel,json=remoteChannel,proto3" json:"remote_channel,omitempty"` // Ethernet channel on remote ASIC
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitNodeInfo) Reset() {
	*x = ExitNodeInfo{}
	mi := &file_topology_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitNodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitNodeInfo) ProtoMessage() {}

func (x *ExitNodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_topology_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitNodeInfo.ProtoReflect.Descriptor instead.
func (*ExitNodeInfo) Descriptor() ([]byte, []int) {
	return file_topology_proto_rawDescGZIP(), []int{3}
}

func (x *ExitNodeInfo) GetLocalAsicId() uint64 {
	if x != nil {
		return x.LocalAsicId
	}
	return 0
}

func (x *ExitNodeInfo) GetLocalChannel() uint32 {
	if x != nil {
		return x.LocalChannel
	}
	return 0
}

func (x *ExitNodeInfo) GetRemoteAsicId() uint64 {
	if x != nil {
		return x.RemoteAsicId
	}
	return 0
}

func (x *ExitNodeInfo) GetRemoteChannel() uint32 {
	if x != nil {
		return x.RemoteChannel
	}
	return 0
}

var File_topology_proto protoreflect.FileDescriptor

const file_topology_proto_rawDesc = "" +
	"\n" +
	"\x0etopology.proto\x12\x16fabricmanager.topology\"\xec\x01\n" +
	"\x14HostPhysicalTopology\x126\n" +
	"\x05asics\x18\x01 \x03(\v2 .fabricmanager.topology.AsicInfoR\x05asics\x12W\n" +
	"\x11local_connections\x18\x02 \x03(\v2*.fabricmanager.topology.LocalEthConnectionR\x10localConnections\x12C\n" +
	"\n" +
	"exit_nodes\x18\x03 \x03(\v2$.fabricmanager.topology.ExitNodeInfoR\texitNodes\"\xa6\x02\n" +
	"\bAsicInfo\x12\x1b\n" +
	"\tunique_id\x18\x01 \x01(\x04R\buniqueId\x12\x1d\n" +
	"\n" +
	"board_type\x18\x02 \x01(\rR\tboardType\x12\x17\n" +
	"\atray_id\x18\x03 \x01(\rR\x06trayId\x12#\n" +
	"\rasic_location\x18\x04 \x01(\rR\fasicLocation\x12\x1b\n" +
	"\tchip_arch\x18\x05 \x01(\tR\bchipArch\x12!\n" +
	"\fmemory_bytes\x18\x06 \x01(\x04R\vmemoryBytes\x12\x1f\n" +
	"\vpci_address\x18\a \x01(\tR\n" +
	"pciAddress\x12\x17\n" +
	"\achip_id\x18\b \x01(\rR\x06chipId\x12&\n" +
	"\x0fis_mmio_capable\x18\t \x01(\bR\risMmioCapable\"\x96\x01\n" +
	"\x12LocalEthConnection\x12\x1e\n" +
	"\vsrc_asic_id\x18\x01 \x01(\x04R\tsrcAsicId\x12\x1f\n" +
	"\vsrc_channel\x18\x02 \x01(\rR\n" +
	"srcChannel\x12\x1e\n" +
	"\vdst_asic_id\x18\x03 \x01(\x04R\tdstAsicId\x12\x1f\n" +
	"\vdst_channel\x18\x04 \x01(\rR\n" +
	"dstChannel\"\xa4\x01\n" +
	"\fExitNodeInfo\x12\"\n" +
	"\rlocal_asic_id\x18\x01 \x01(\x04R\vlocalAsicId\x12#\n" +
	"\rlocal_channel\x18\x02 \x01(\rR\flocalChannel\x12$\n" +
	"\x0eremote_asic_id\x18\x03 \x01(\x04R\fremoteAsicId\x12%\n" +
	"\x0eremote_channel\x18\x04 \x01(\rR\rremoteChannelb\x06proto3"

var (
	file_topology_proto_rawDescOnce sync.Once
	file_topology_proto_rawDescData []byte
)

func file_topology_proto_rawDescGZIP() []byte {
	file_topology_proto_rawDescOnce.Do(func() {
		file_topology_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_topology_proto_rawDesc), len(file_topology_proto_rawDesc)))
	})
	return file_topology_proto_rawDescData
}

var file_topology_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_topology_proto_goTypes = []any{
	(*HostPhysicalTopology)(nil), // 0: fabricmanager.topology.HostPhysicalTopology
	(*AsicInfo)(nil),             // 1: fabricmanager.topology.AsicInfo
	(*LocalEthConnection)(nil),   // 2: fabricmanager.topology.LocalEthConnection
	(*ExitNodeInfo)(nil),         // 3: fabricmanager.topology.ExitNodeInfo
}
var file_topology_proto_depIdxs = []int32{
	1, // 0: fabricmanager.topology.HostPhysicalTopology.asics:type_name -> fabricmanager.topology.AsicInfo
	2, // 1: fabricmanager.topology.HostPhysicalTopology.local_connections:type_name -> fabricmanager.topology.LocalEthConnection
	3, // 2: fabricmanager.topology.HostPhysicalTopology.exit_nodes:type_name -> fabricmanager.topology.ExitNodeInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_topology_proto_init() }
func file_topology_proto_init() {
	if File_topology_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_topology_proto_rawDesc), len(file_topology_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_topology_proto_goTypes,
		DependencyIndexes: file_topology_proto_depIdxs,
		MessageInfos:      file_topology_proto_msgTypes,
	}.Build()
	File_topology_proto = out.File
	file_topology_proto_goTypes = nil
	file_topology_proto_depIdxs = nil
}
