// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.33.2
// source: agent.proto

package agent

import (
	topology "github.com/tenstorrent/tt-dra-driver/internal/fabricmanager/proto/topology"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Outcome of a RediscoverTopology call. Kept in the agent package because it
// describes agent-local behaviour; the controller maps it to its own
// user-facing status in orchestrator.proto.
type RediscoverStatus int32

const (
	RediscoverStatus_REDISCOVER_UNKNOWN RediscoverStatus = 0
	// UMD topology discovery ran successfully; physical_topology and
	// cluster_descriptor_yaml are populated from the fresh cluster descriptor.
	RediscoverStatus_REDISCOVER_OK RediscoverStatus = 1
	// UMD discovery failed; the response carries a best-effort fallback
	// topology (scanned from /dev/tenstorrent/*) and no cluster descriptor.
	// The controller may choose to accept or reject this.
	RediscoverStatus_REDISCOVER_FALLBACK RediscoverStatus = 2
	// Another rediscovery is already in flight on this agent. No state was
	// mutated; the caller may retry.
	RediscoverStatus_REDISCOVER_ALREADY_IN_PROGRESS RediscoverStatus = 3
	// Rediscovery threw an unexpected error. physical_topology is not
	// populated; message carries a human-readable reason.
	RediscoverStatus_REDISCOVER_FAILED RediscoverStatus = 4
)

// Enum value maps for RediscoverStatus.
var (
	RediscoverStatus_name = map[int32]string{
		0: "REDISCOVER_UNKNOWN",
		1: "REDISCOVER_OK",
		2: "REDISCOVER_FALLBACK",
		3: "REDISCOVER_ALREADY_IN_PROGRESS",
		4: "REDISCOVER_FAILED",
	}
	RediscoverStatus_value = map[string]int32{
		"REDISCOVER_UNKNOWN":             0,
		"REDISCOVER_OK":                  1,
		"REDISCOVER_FALLBACK":            2,
		"REDISCOVER_ALREADY_IN_PROGRESS": 3,
		"REDISCOVER_FAILED":              4,
	}
)

func (x RediscoverStatus) Enum() *RediscoverStatus {
	p := new(RediscoverStatus)
	*p = x
	return p
}

func (x RediscoverStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RediscoverStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (RediscoverStatus) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x RediscoverStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RediscoverStatus.Descriptor instead.
func (RediscoverStatus) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

type GetTopologyStatus int32

const (
	GetTopologyStatus_TOPOLOGY_OK             GetTopologyStatus = 0
	GetTopologyStatus_TOPOLOGY_NOT_DISCOVERED GetTopologyStatus = 1
)

// Enum value maps for GetTopologyStatus.
var (
	GetTopologyStatus_name = map[int32]string{
		0: "TOPOLOGY_OK",
		1: "TOPOLOGY_NOT_DISCOVERED",
	}
	GetTopologyStatus_value = map[string]int32{
		"TOPOLOGY_OK":             0,
		"TOPOLOGY_NOT_DISCOVERED": 1,
	}
)

func (x GetTopologyStatus) Enum() *GetTopologyStatus {
	p := new(GetTopologyStatus)
	*p = x
	return p
}

func (x GetTopologyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetTopologyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[1].Descriptor()
}

func (GetTopologyStatus) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[1]
}

func (x GetTopologyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetTopologyStatus.Descriptor instead.
func (GetTopologyStatus) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

// Per-link outcome embedded in RetrainLinksResponse.results. Status values
// match the per-link enum below; one result is emitted for every entry in
// the request, in request order.
type LinkRetrainStatus int32

const (
	LinkRetrainStatus_LINK_RETRAIN_UNKNOWN LinkRetrainStatus = 0
	// The retrain was triggered and the FW acknowledged the operation. On
	// Blackhole the FW result word is also returned in
	// LinkRetrainResult.blackhole_fw_result.
	LinkRetrainStatus_LINK_RETRAIN_OK LinkRetrainStatus = 1
	// The chip / channel reference does not name a real ethernet link on
	// this host (chip not present, channel out of range for the chip's
	// architecture, etc.). No FW interaction was attempted.
	LinkRetrainStatus_LINK_RETRAIN_INVALID_LINK LinkRetrainStatus = 2
	// The architecture of the named chip is not supported by tt-ethtool's
	// retrain path (e.g. an unsupported / unknown ARCH).
	LinkRetrainStatus_LINK_RETRAIN_UNSUPPORTED_ARCH LinkRetrainStatus = 3
	// FW interaction failed (mailbox timeout, retrain ack timeout, UMD I/O
	// error, etc.). The message field carries a human-readable reason.
	LinkRetrainStatus_LINK_RETRAIN_FAILED LinkRetrainStatus = 4
)

// Enum value maps for LinkRetrainStatus.
var (
	LinkRetrainStatus_name = map[int32]string{
		0: "LINK_RETRAIN_UNKNOWN",
		1: "LINK_RETRAIN_OK",
		2: "LINK_RETRAIN_INVALID_LINK",
		3: "LINK_RETRAIN_UNSUPPORTED_ARCH",
		4: "LINK_RETRAIN_FAILED",
	}
	LinkRetrainStatus_value = map[string]int32{
		"LINK_RETRAIN_UNKNOWN":          0,
		"LINK_RETRAIN_OK":               1,
		"LINK_RETRAIN_INVALID_LINK":     2,
		"LINK_RETRAIN_UNSUPPORTED_ARCH": 3,
		"LINK_RETRAIN_FAILED":           4,
	}
)

func (x LinkRetrainStatus) Enum() *LinkRetrainStatus {
	p := new(LinkRetrainStatus)
	*p = x
	return p
}

func (x LinkRetrainStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LinkRetrainStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[2].Descriptor()
}

func (LinkRetrainStatus) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[2]
}

func (x LinkRetrainStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LinkRetrainStatus.Descriptor instead.
func (LinkRetrainStatus) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

// Top-level summary of how the batch went. Per-link detail (including
// failure messages) lives on each LinkRetrainResult in `results`.
type RetrainLinksStatus int32

const (
	RetrainLinksStatus_RETRAIN_LINKS_UNKNOWN RetrainLinksStatus = 0
	// Every link in the request retrained successfully.
	RetrainLinksStatus_RETRAIN_LINKS_OK RetrainLinksStatus = 1
	// At least one link succeeded and at least one failed. Inspect
	// `results` for per-link detail.
	RetrainLinksStatus_RETRAIN_LINKS_PARTIAL RetrainLinksStatus = 2
	// No link in the request succeeded. `results` still holds one entry
	// per requested link describing why each one failed.
	RetrainLinksStatus_RETRAIN_LINKS_FAILED RetrainLinksStatus = 3
	// The agent has no link-retrain backend installed. This is a
	// configuration error on the agent side; callers should not retry.
	// `results` is empty in this case.
	RetrainLinksStatus_RETRAIN_LINKS_UNAVAILABLE RetrainLinksStatus = 4
	// The request carried zero links. `results` is empty.
	RetrainLinksStatus_RETRAIN_LINKS_EMPTY_REQUEST RetrainLinksStatus = 5
)

// Enum value maps for RetrainLinksStatus.
var (
	RetrainLinksStatus_name = map[int32]string{
		0: "RETRAIN_LINKS_UNKNOWN",
		1: "RETRAIN_LINKS_OK",
		2: "RETRAIN_LINKS_PARTIAL",
		3: "RETRAIN_LINKS_FAILED",
		4: "RETRAIN_LINKS_UNAVAILABLE",
		5: "RETRAIN_LINKS_EMPTY_REQUEST",
	}
	RetrainLinksStatus_value = map[string]int32{
		"RETRAIN_LINKS_UNKNOWN":       0,
		"RETRAIN_LINKS_OK":            1,
		"RETRAIN_LINKS_PARTIAL":       2,
		"RETRAIN_LINKS_FAILED":        3,
		"RETRAIN_LINKS_UNAVAILABLE":   4,
		"RETRAIN_LINKS_EMPTY_REQUEST": 5,
	}
)

func (x RetrainLinksStatus) Enum() *RetrainLinksStatus {
	p := new(RetrainLinksStatus)
	*p = x
	return p
}

func (x RetrainLinksStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RetrainLinksStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[3].Descriptor()
}

func (RetrainLinksStatus) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[3]
}

func (x RetrainLinksStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RetrainLinksStatus.Descriptor instead.
func (RetrainLinksStatus) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RediscoverTopologyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RediscoverTopologyRequest) Reset() {
	*x = RediscoverTopologyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RediscoverTopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RediscoverTopologyRequest) ProtoMessage() {}

func (x *RediscoverTopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RediscoverTopologyRequest.ProtoReflect.Descriptor instead.
func (*RediscoverTopologyRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

type RediscoverTopologyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status RediscoverStatus `protobuf:"varint,1,opt,name=status,proto3,enum=fabricmanager.agent.RediscoverStatus" json:"status,omitempty"`
	// Human-readable detail: success counts, failure reason, or the reason a
	// rediscovery was rejected.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Present when status is REDISCOVER_OK or REDISCOVER_FALLBACK.
	PhysicalTopology *topology.HostPhysicalTopology `protobuf:"bytes,3,opt,name=physical_topology,json=physicalTopology,proto3" json:"physical_topology,omitempty"`
	// Present when status is REDISCOVER_OK (UMD path); empty on the fallback
	// path because there is no cluster descriptor to serialise.
	ClusterDescriptorYaml string `protobuf:"bytes,4,opt,name=cluster_descriptor_yaml,json=clusterDescriptorYaml,proto3" json:"cluster_descriptor_yaml,omitempty"`
}

func (x *RediscoverTopologyResponse) Reset() {
	*x = RediscoverTopologyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RediscoverTopologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RediscoverTopologyResponse) ProtoMessage() {}

func (x *RediscoverTopologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RediscoverTopologyResponse.ProtoReflect.Descriptor instead.
func (*RediscoverTopologyResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *RediscoverTopologyResponse) GetStatus() RediscoverStatus {
	if x != nil {
		return x.Status
	}
	return RediscoverStatus_REDISCOVER_UNKNOWN
}

func (x *RediscoverTopologyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RediscoverTopologyResponse) GetPhysicalTopology() *topology.HostPhysicalTopology {
	if x != nil {
		return x.PhysicalTopology
	}
	return nil
}

func (x *RediscoverTopologyResponse) GetClusterDescriptorYaml() string {
	if x != nil {
		return x.ClusterDescriptorYaml
	}
	return ""
}

type GetTopologyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetTopologyRequest) Reset() {
	*x = GetTopologyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopologyRequest) ProtoMessage() {}

func (x *GetTopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopologyRequest.ProtoReflect.Descriptor instead.
func (*GetTopologyRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

type GetTopologyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status                GetTopologyStatus              `protobuf:"varint,1,opt,name=status,proto3,enum=fabricmanager.agent.GetTopologyStatus" json:"status,omitempty"`
	PhysicalTopology      *topology.HostPhysicalTopology `protobuf:"bytes,2,opt,name=physical_topology,json=physicalTopology,proto3" json:"physical_topology,omitempty"`
	ClusterDescriptorYaml string                         `protobuf:"bytes,3,opt,name=cluster_descriptor_yaml,json=clusterDescriptorYaml,proto3" json:"cluster_descriptor_yaml,omitempty"`
}

func (x *GetTopologyResponse) Reset() {
	*x = GetTopologyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTopologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopologyResponse) ProtoMessage() {}

func (x *GetTopologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopologyResponse.ProtoReflect.Descriptor instead.
func (*GetTopologyResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *GetTopologyResponse) GetStatus() GetTopologyStatus {
	if x != nil {
		return x.Status
	}
	return GetTopologyStatus_TOPOLOGY_OK
}

func (x *GetTopologyResponse) GetPhysicalTopology() *topology.HostPhysicalTopology {
	if x != nil {
		return x.PhysicalTopology
	}
	return nil
}

func (x *GetTopologyResponse) GetClusterDescriptorYaml() string {
	if x != nil {
		return x.ClusterDescriptorYaml
	}
	return ""
}

type WatchTopologyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WatchTopologyRequest) Reset() {
	*x = WatchTopologyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchTopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchTopologyRequest) ProtoMessage() {}

func (x *WatchTopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchTopologyRequest.ProtoReflect.Descriptor instead.
func (*WatchTopologyRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

// One snapshot of the agent's topology state, as streamed by WatchTopology.
// The status / topology / YAML fields carry exactly what a GetTopology call
// made at that instant would have returned.
type WatchTopologyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status                GetTopologyStatus              `protobuf:"varint,1,opt,name=status,proto3,enum=fabricmanager.agent.GetTopologyStatus" json:"status,omitempty"`
	PhysicalTopology      *topology.HostPhysicalTopology `protobuf:"bytes,2,opt,name=physical_topology,json=physicalTopology,proto3" json:"physical_topology,omitempty"`
	ClusterDescriptorYaml string                         `protobuf:"bytes,3,opt,name=cluster_descriptor_yaml,json=clusterDescriptorYaml,proto3" json:"cluster_descriptor_yaml,omitempty"`
	// Generation counter of the agent's topology state, incremented every
	// time the agent installs a discovery result. It is strictly increasing
	// within a stream but not contiguous: rediscoveries that did not change
	// the topology bump it without producing a message. It resets when the
	// agent restarts, so it is only meaningful for ordering messages within
	// one stream, not for comparing across connections.
	Version uint64 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *WatchTopologyResponse) Reset() {
	*x = WatchTopologyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchTopologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchTopologyResponse) ProtoMessage() {}

func (x *WatchTopologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchTopologyResponse.ProtoReflect.Descriptor instead.
func (*WatchTopologyResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *WatchTopologyResponse) GetStatus() GetTopologyStatus {
	if x != nil {
		return x.Status
	}
	return GetTopologyStatus_TOPOLOGY_OK
}

func (x *WatchTopologyResponse) GetPhysicalTopology() *topology.HostPhysicalTopology {
	if x != nil {
		return x.PhysicalTopology
	}
	return nil
}

func (x *WatchTopologyResponse) GetClusterDescriptorYaml() string {
	if x != nil {
		return x.ClusterDescriptorYaml
	}
	return ""
}

func (x *WatchTopologyResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// Identifies a single link to retrain plus the architecture-specific
// tunables honoured by the FW. Wormhole has no tunables today; the
// blackhole_* fields are ignored on Wormhole chips.
type LinkRetrainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Logical chip id within the host (matches HostPhysicalTopology.Asic.chip_id
	// and the chip_id reported by tt-ethtool list).
	ChipId uint32 `protobuf:"varint,1,opt,name=chip_id,json=chipId,proto3" json:"chip_id,omitempty"`
	// Ethernet channel index on that chip.
	Channel uint32 `protobuf:"varint,2,opt,name=channel,proto3" json:"channel,omitempty"`
	// Blackhole-only. Selects the reinit flavour for ETH_MSG_PORT_REINIT_MACPCS:
	//
	//	0 = MAC only (SERDES already trained)
	//	1 = MAC + SERDES retrain
	//	2 = MAC + SERDES from reset (default when this field is zero)
	//	3 = MAC + SERDES from reset + TX barrier
	//
	// Ignored on Wormhole.
	BlackholeReinitOption uint32 `protobuf:"varint,3,opt,name=blackhole_reinit_option,json=blackholeReinitOption,proto3" json:"blackhole_reinit_option,omitempty"`
	// Blackhole-only. FW retry budget for the reinit. Zero means "use the
	// agent default" (currently 1, matching the tt-ethtool CLI default).
	// Ignored on Wormhole.
	BlackholeRetries uint32 `protobuf:"varint,4,opt,name=blackhole_retries,json=blackholeRetries,proto3" json:"blackhole_retries,omitempty"`
}

func (x *LinkRetrainRequest) Reset() {
	*x = LinkRetrainRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkRetrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkRetrainRequest) ProtoMessage() {}

func (x *LinkRetrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkRetrainRequest.ProtoReflect.Descriptor instead.
func (*LinkRetrainRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *LinkRetrainRequest) GetChipId() uint32 {
	if x != nil {
		return x.ChipId
	}
	return 0
}

func (x *LinkRetrainRequest) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *LinkRetrainRequest) GetBlackholeReinitOption() uint32 {
	if x != nil {
		return x.BlackholeReinitOption
	}
	return 0
}

func (x *LinkRetrainRequest) GetBlackholeRetries() uint32 {
	if x != nil {
		return x.BlackholeRetries
	}
	return 0
}

// Per-link result. Echoes the chip_id / channel from the request so callers
// can correlate results without relying on positional ordering (though the
// agent does preserve request order).
type LinkRetrainResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChipId  uint32            `protobuf:"varint,1,opt,name=chip_id,json=chipId,proto3" json:"chip_id,omitempty"`
	Channel uint32            `protobuf:"varint,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Status  LinkRetrainStatus `protobuf:"varint,3,opt,name=status,proto3,enum=fabricmanager.agent.LinkRetrainStatus" json:"status,omitempty"`
	// Human-readable detail. Empty on success; populated on every error path.
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// Architecture string of the chip that was retrained, e.g. "wormhole_b0"
	// or "blackhole". Empty if the request never reached the FW (invalid
	// link, no backend installed).
	ChipArch string `protobuf:"bytes,5,opt,name=chip_arch,json=chipArch,proto3" json:"chip_arch,omitempty"`
	// Blackhole-only. Mailbox arg0 returned by the FW after
	// ETH_MSG_PORT_REINIT_MACPCS completes (echo of tt-ethtool's
	// ReinitResult::fw_result). Always 0 on Wormhole or on error paths.
	BlackholeFwResult uint32 `protobuf:"varint,6,opt,name=blackhole_fw_result,json=blackholeFwResult,proto3" json:"blackhole_fw_result,omitempty"`
}

func (x *LinkRetrainResult) Reset() {
	*x = LinkRetrainResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkRetrainResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkRetrainResult) ProtoMessage() {}

func (x *LinkRetrainResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkRetrainResult.ProtoReflect.Descriptor instead.
func (*LinkRetrainResult) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *LinkRetrainResult) GetChipId() uint32 {
	if x != nil {
		return x.ChipId
	}
	return 0
}

func (x *LinkRetrainResult) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *LinkRetrainResult) GetStatus() LinkRetrainStatus {
	if x != nil {
		return x.Status
	}
	return LinkRetrainStatus_LINK_RETRAIN_UNKNOWN
}

func (x *LinkRetrainResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LinkRetrainResult) GetChipArch() string {
	if x != nil {
		return x.ChipArch
	}
	return ""
}

func (x *LinkRetrainResult) GetBlackholeFwResult() uint32 {
	if x != nil {
		return x.BlackholeFwResult
	}
	return 0
}

type RetrainLinksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Links to retrain, processed sequentially in this order. An empty list
	// is treated as a no-op and reported as RETRAIN_LINKS_EMPTY_REQUEST.
	Links []*LinkRetrainRequest `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
}

func (x *RetrainLinksRequest) Reset() {
	*x = RetrainLinksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrainLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrainLinksRequest) ProtoMessage() {}

func (x *RetrainLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrainLinksRequest.ProtoReflect.Descriptor instead.
func (*RetrainLinksRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *RetrainLinksRequest) GetLinks() []*LinkRetrainRequest {
	if x != nil {
		return x.Links
	}
	return nil
}

type RetrainLinksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status RetrainLinksStatus `protobuf:"varint,1,opt,name=status,proto3,enum=fabricmanager.agent.RetrainLinksStatus" json:"status,omitempty"`
	// Optional top-level summary, e.g. "3/4 links retrained successfully".
	// Per-link diagnostics live on each LinkRetrainResult.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// One entry per requested link, in request order. Empty when status is
	// RETRAIN_LINKS_UNAVAILABLE or RETRAIN_LINKS_EMPTY_REQUEST.
	Results []*LinkRetrainResult `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *RetrainLinksResponse) Reset() {
	*x = RetrainLinksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrainLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrainLinksResponse) ProtoMessage() {}

func (x *RetrainLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrainLinksResponse.ProtoReflect.Descriptor instead.
func (*RetrainLinksResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *RetrainLinksResponse) GetStatus() RetrainLinksStatus {
	if x != nil {
		return x.Status
	}
	return RetrainLinksStatus_RETRAIN_LINKS_UNKNOWN
}

func (x *RetrainLinksResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RetrainLinksResponse) GetResults() []*LinkRetrainResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_agent_proto protoreflect.FileDescriptor

var file_agent_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x66,
	0x61, 0x62, 0x72, 0x69, 0x63, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x1a, 0x0e, 0x74, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x27, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x28, 0x0a, 0x0c, 0x50,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x1b, 0x0a, 0x19, 0x52, 0x65, 0x64, 0x69, 0x73, 0x63, 0x6f,
	0x76, 0x65, 0x72, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x88, 0x02, 0x0a, 0x1a, 0x52, 0x65, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65,
	0x72, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3d, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x25, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x59, 0x0a, 0x11, 0x70, 0x68,
	0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x5f, 0x74, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x74, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x2e, 0x48,
	0x6f, 0x73, 0x74, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x54, 0x6f, 0x70, 0x6f, 0x6c,
	0x6f, 0x67, 0x79, 0x52, 0x10, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x54, 0x6f, 0x70,
	0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x12, 0x36, 0x0a, 0x17, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x5f, 0x79, 0x61, 0x6d, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x59, 0x61, 0x6d, 0x6c, 0x22, 0x14, 0x0a,
	0x12, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0xe8, 0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x6f, 0x6c,
	0x6f, 0x67, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x66, 0x61,
	0x62, 0x72, 0x69, 0x63, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x59, 0x0a, 0x11, 0x70,
	0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x5f, 0x74, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x74, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x2e,
	0x48, 0x6f, 0x73, 0x74, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x54, 0x6f, 0x70, 0x6f,
	0x6c, 0x6f, 0x67, 0x79, 0x52, 0x10, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x54, 0x6f,
	0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x12, 0x36, 0x0a, 0x17, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x5f, 0x79, 0x61, 0x6d,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x59, 0x61, 0x6d, 0x6c, 0x22, 0x16,
	0x0a, 0x14, 0x57, 0x61, 0x74, 0x63, 0x68, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x84, 0x02, 0x0a, 0x15, 0x57, 0x61, 0x74, 0x63, 0x68,
	0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x26, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f,
	0x67, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x59, 0x0a, 0x11, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x5f, 0x74, 0x6f, 0x70,
	0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x66, 0x61,
	0x62, 0x72, 0x69, 0x63, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x74, 0x6f, 0x70, 0x6f,
	0x6c, 0x6f, 0x67, 0x79, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61,
	0x6c, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x52, 0x10, 0x70, 0x68, 0x79, 0x73, 0x69,
	0x63, 0x61, 0x6c, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x12, 0x36, 0x0a, 0x17, 0x63,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f,
	0x72, 0x5f, 0x79, 0x61, 0x6d, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x59,
	0x61, 0x6d, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xac, 0x01,
	0x0a, 0x12, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x68, 0x69, 0x70, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x63, 0x68, 0x69, 0x70, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x36, 0x0a, 0x17, 0x62, 0x6c, 0x61, 0x63, 0x6b,
	0x68, 0x6f, 0x6c, 0x65, 0x5f, 0x72, 0x65, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x15, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x68,
	0x6f, 0x6c, 0x65, 0x52, 0x65, 0x69, 0x6e, 0x69, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x2b, 0x0a, 0x11, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x68, 0x6f, 0x6c, 0x65, 0x5f, 0x72, 0x65, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10, 0x62, 0x6c, 0x61, 0x63,
	0x6b, 0x68, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0xed, 0x01, 0x0a,
	0x11, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x68, 0x69, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x63, 0x68, 0x69, 0x70, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x3e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x69, 0x6e, 0x6b,
	0x52, 0x65, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x63, 0x68, 0x69, 0x70, 0x5f, 0x61, 0x72, 0x63, 0x68, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x68, 0x69, 0x70, 0x41, 0x72, 0x63, 0x68, 0x12, 0x2e, 0x0a, 0x13,
	0x62, 0x6c, 0x61, 0x63, 0x6b, 0x68, 0x6f, 0x6c, 0x65, 0x5f, 0x66, 0x77, 0x5f, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x11, 0x62, 0x6c, 0x61, 0x63, 0x6b,
	0x68, 0x6f, 0x6c, 0x65, 0x46, 0x77, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x54, 0x0a, 0x13,
	0x52, 0x65, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x27, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x74,
	0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x05, 0x6c, 0x69, 0x6e,
	0x6b, 0x73, 0x22, 0xb3, 0x01, 0x0a, 0x14, 0x52, 0x65, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x4c, 0x69,
	0x6e, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x66, 0x61,
	0x62, 0x72, 0x69, 0x63, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x40, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x69,
	0x6e, 0x6b, 0x52, 0x65, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52,
	0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x2a, 0x91, 0x01, 0x0a, 0x10, 0x52, 0x65, 0x64,
	0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a,
	0x12, 0x52, 0x45, 0x44, 0x49, 0x53, 0x43, 0x4f, 0x56, 0x45, 0x52, 0x5f, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x45, 0x44, 0x49, 0x53, 0x43, 0x4f,
	0x56, 0x45, 0x52, 0x5f, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x45, 0x44, 0x49,
	0x53, 0x43, 0x4f, 0x56, 0x45, 0x52, 0x5f, 0x46, 0x41, 0x4c, 0x4c, 0x42, 0x41, 0x43, 0x4b, 0x10,
	0x02, 0x12, 0x22, 0x0a, 0x1e, 0x52, 0x45, 0x44, 0x49, 0x53, 0x43, 0x4f, 0x56, 0x45, 0x52, 0x5f,
	0x41, 0x4c, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x49, 0x4e, 0x5f, 0x50, 0x52, 0x4f, 0x47, 0x52,
	0x45, 0x53, 0x53, 0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x45, 0x44, 0x49, 0x53, 0x43, 0x4f,
	0x56, 0x45, 0x52, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x04, 0x2a, 0x41, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x4f, 0x50, 0x4f, 0x4c, 0x4f, 0x47, 0x59, 0x5f, 0x4f, 0x4b,
	0x10, 0x00, 0x12, 0x1b, 0x0a, 0x17, 0x54, 0x4f, 0x50, 0x4f, 0x4c, 0x4f, 0x47, 0x59, 0x5f, 0x4e,
	0x4f, 0x54, 0x5f, 0x44, 0x49, 0x53, 0x43, 0x4f, 0x56, 0x45, 0x52, 0x45, 0x44, 0x10, 0x01, 0x2a,
	0x9d, 0x01, 0x0a, 0x11, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x14, 0x4c, 0x49, 0x4e, 0x4b, 0x5f, 0x52, 0x45,
	0x54, 0x52, 0x41, 0x49, 0x4e, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x13, 0x0a, 0x0f, 0x4c, 0x49, 0x4e, 0x4b, 0x5f, 0x52, 0x45, 0x54, 0x52, 0x41, 0x49, 0x4e, 0x5f,
	0x4f, 0x4b, 0x10, 0x01, 0x12, 0x1d, 0x0a, 0x19, 0x4c, 0x49, 0x4e, 0x4b, 0x5f, 0x52, 0x45, 0x54,
	0x52, 0x41, 0x49, 0x4e, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x4c, 0x49, 0x4e,
	0x4b, 0x10, 0x02, 0x12, 0x21, 0x0a, 0x1d, 0x4c, 0x49, 0x4e, 0x4b, 0x5f, 0x52, 0x45, 0x54, 0x52,
	0x41, 0x49, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x55, 0x50, 0x50, 0x4f, 0x52, 0x54, 0x45, 0x44, 0x5f,
	0x41, 0x52, 0x43, 0x48, 0x10, 0x03, 0x12, 0x17, 0x0a, 0x13, 0x4c, 0x49, 0x4e, 0x4b, 0x5f, 0x52,
	0x45, 0x54, 0x52, 0x41, 0x49, 0x4e, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x04, 0x2a,
	0xba, 0x01, 0x0a, 0x12, 0x52, 0x65, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x4c, 0x69, 0x6e, 0x6b, 0x73,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x19, 0x0a, 0x15, 0x52, 0x45, 0x54, 0x52, 0x41, 0x49,
	0x4e, 0x5f, 0x4c, 0x49, 0x4e, 0x4b, 0x53, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x45, 0x54, 0x52, 0x41, 0x49, 0x4e, 0x5f, 0x4c, 0x49, 0x4e,
	0x4b, 0x53, 0x5f, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x52, 0x45, 0x54, 0x52, 0x41,
	0x49, 0x4e, 0x5f, 0x4c, 0x49, 0x4e, 0x4b, 0x53, 0x5f, 0x50, 0x41, 0x52, 0x54, 0x49, 0x41, 0x4c,
	0x10, 0x02, 0x12, 0x18, 0x0a, 0x14, 0x52, 0x45, 0x54, 0x52, 0x41, 0x49, 0x4e, 0x5f, 0x4c, 0x49,
	0x4e, 0x4b, 0x53, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x12, 0x1d, 0x0a, 0x19,
	0x52, 0x45, 0x54, 0x52, 0x41, 0x49, 0x4e, 0x5f, 0x4c, 0x49, 0x4e, 0x4b, 0x53, 0x5f, 0x55, 0x4e,
	0x41, 0x56, 0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x04, 0x12, 0x1f, 0x0a, 0x1b, 0x52,
	0x45, 0x54, 0x52, 0x41, 0x49, 0x4e, 0x5f, 0x4c, 0x49, 0x4e, 0x4b, 0x53, 0x5f, 0x45, 0x4d, 0x50,
	0x54, 0x59, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x05, 0x32, 0x8d, 0x04, 0x0a,
	0x0c, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4d, 0x0a,
	0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x20, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x77, 0x0a, 0x12,
	0x52, 0x65, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f,
	0x67, 0x79, 0x12, 0x2e, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x64, 0x69, 0x73, 0x63, 0x6f,
	0x76, 0x65, 0x72, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x64, 0x69, 0x73, 0x63, 0x6f,
	0x76, 0x65, 0x72, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x62, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x6f,
	0x6c, 0x6f, 0x67, 0x79, 0x12, 0x27, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f,
	0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e,
	0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6a, 0x0a, 0x0d, 0x57, 0x61, 0x74,
	0x63, 0x68, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x12, 0x29, 0x2e, 0x66, 0x61, 0x62,
	0x72, 0x69, 0x63, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x57, 0x61, 0x74, 0x63,
	0x68, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x65, 0x0a, 0x0c, 0x52, 0x65, 0x74, 0x72, 0x61, 0x69, 0x6e,
	0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x28, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x74, 0x72,
	0x61, 0x69, 0x6e, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x29, 0x2e, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x4c, 0x69, 0x6e,
	0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData = file_agent_proto_rawDesc
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_agent_proto_rawDescData)
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_agent_proto_goTypes = []interface{}{
	(RediscoverStatus)(0),                 // 0: fabricmanager.agent.RediscoverStatus
	(GetTopologyStatus)(0),                // 1: fabricmanager.agent.GetTopologyStatus
	(LinkRetrainStatus)(0),                // 2: fabricmanager.agent.LinkRetrainStatus
	(RetrainLinksStatus)(0),               // 3: fabricmanager.agent.RetrainLinksStatus
	(*PingRequest)(nil),                   // 4: fabricmanager.agent.PingRequest
	(*PingResponse)(nil),                  // 5: fabricmanager.agent.PingResponse
	(*RediscoverTopologyRequest)(nil),     // 6: fabricmanager.agent.RediscoverTopologyRequest
	(*RediscoverTopologyResponse)(nil),    // 7: fabricmanager.agent.RediscoverTopologyResponse
	(*GetTopologyRequest)(nil),            // 8: fabricmanager.agent.GetTopologyRequest
	(*GetTopologyResponse)(nil),           // 9: fabricmanager.agent.GetTopologyResponse
	(*WatchTopologyRequest)(nil),          // 10: fabricmanager.agent.WatchTopologyRequest
	(*WatchTopologyResponse)(nil),         // 11: fabricmanager.agent.WatchTopologyResponse
	(*LinkRetrainRequest)(nil),            // 12: fabricmanager.agent.LinkRetrainRequest
	(*LinkRetrainResult)(nil),             // 13: fabricmanager.agent.LinkRetrainResult
	(*RetrainLinksRequest)(nil),           // 14: fabricmanager.agent.RetrainLinksRequest
	(*RetrainLinksResponse)(nil),          // 15: fabricmanager.agent.RetrainLinksResponse
	(*topology.HostPhysicalTopology)(nil), // 16: fabricmanager.topology.HostPhysicalTopology
}
var file_agent_proto_depIdxs = []int32{
	0,  // 0: fabricmanager.agent.RediscoverTopologyResponse.status:type_name -> fabricmanager.agent.RediscoverStatus
	16, // 1: fabricmanager.agent.RediscoverTopologyResponse.physical_topology:type_name -> fabricmanager.topology.HostPhysicalTopology
	1,  // 2: fabricmanager.agent.GetTopologyResponse.status:type_name -> fabricmanager.agent.GetTopologyStatus
	16, // 3: fabricmanager.agent.GetTopologyResponse.physical_topology:type_name -> fabricmanager.topology.HostPhysicalTopology
	1,  // 4: fabricmanager.agent.WatchTopologyResponse.status:type_name -> fabricmanager.agent.GetTopologyStatus
	16, // 5: fabricmanager.agent.WatchTopologyResponse.physical_topology:type_name -> fabricmanager.topology.HostPhysicalTopology
	2,  // 6: fabricmanager.agent.LinkRetrainResult.status:type_name -> fabricmanager.agent.LinkRetrainStatus
	12, // 7: fabricmanager.agent.RetrainLinksRequest.links:type_name -> fabricmanager.agent.LinkRetrainRequest
	3,  // 8: fabricmanager.agent.RetrainLinksResponse.status:type_name -> fabricmanager.agent.RetrainLinksStatus
	13, // 9: fabricmanager.agent.RetrainLinksResponse.results:type_name -> fabricmanager.agent.LinkRetrainResult
	4,  // 10: fabricmanager.agent.AgentService.Ping:input_type -> fabricmanager.agent.PingRequest
	6,  // 11: fabricmanager.agent.AgentService.RediscoverTopology:input_type -> fabricmanager.agent.RediscoverTopologyRequest
	8,  // 12: fabricmanager.agent.AgentService.GetTopology:input_type -> fabricmanager.agent.GetTopologyRequest
	10, // 13: fabricmanager.agent.AgentService.WatchTopology:input_type -> fabricmanager.agent.WatchTopologyRequest
	14, // 14: fabricmanager.agent.AgentService.RetrainLinks:input_type -> fabricmanager.agent.RetrainLinksRequest
	5,  // 15: fabricmanager.agent.AgentService.Ping:output_type -> fabricmanager.agent.PingResponse
	7,  // 16: fabricmanager.agent.AgentService.RediscoverTopology:output_type -> fabricmanager.agent.RediscoverTopologyResponse
	9,  // 17: fabricmanager.agent.AgentService.GetTopology:output_type -> fabricmanager.agent.GetTopologyResponse
	11, // 18: fabricmanager.agent.AgentService.WatchTopology:output_type -> fabricmanager.agent.WatchTopologyResponse
	15, // 19: fabricmanager.agent.AgentService.RetrainLinks:output_type -> fabricmanager.agent.RetrainLinksResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_agent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RediscoverTopologyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RediscoverTopologyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTopologyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTopologyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchTopologyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchTopologyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkRetrainRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkRetrainResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrainLinksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrainLinksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_agent_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_rawDesc = nil
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
