// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: agent.proto

package agent

import (
	topology "github.com/tenstorrent/tt-dra-driver/internal/fabricmanager/proto/topology"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Outcome of a RediscoverTopology call. Kept in the agent package because it
// describes agent-local behaviour; the controller maps it to its own
// user-facing status in orchestrator.proto.
type RediscoverStatus int32

const (
	RediscoverStatus_REDISCOVER_UNKNOWN RediscoverStatus = 0
	// UMD topology discovery ran successfully; physical_topology and
	// cluster_descriptor_yaml are populated from the fresh cluster descriptor.
	RediscoverStatus_REDISCOVER_OK RediscoverStatus = 1
	// UMD discovery failed; the response carries a best-effort fallback
	// topology (scanned from /dev/tenstorrent/*) and no cluster descriptor.
	// The controller may choose to accept or reject this.
	RediscoverStatus_REDISCOVER_FALLBACK RediscoverStatus = 2
	// Another rediscovery is already in flight on this agent. No state was
	// mutated; the caller may retry.
	RediscoverStatus_REDISCOVER_ALREADY_IN_PROGRESS RediscoverStatus = 3
	// Rediscovery threw an unexpected error. physical_topology is not
	// populated; message carries a human-readable reason.
	RediscoverStatus_REDISCOVER_FAILED RediscoverStatus = 4
)

// Enum value maps for RediscoverStatus.
var (
	RediscoverStatus_name = map[int32]string{
		0: "REDISCOVER_UNKNOWN",
		1: "REDISCOVER_OK",
		2: "REDISCOVER_FALLBACK",
		3: "REDISCOVER_ALREADY_IN_PROGRESS",
		4: "REDISCOVER_FAILED",
	}
	RediscoverStatus_value = map[string]int32{
		"REDISCOVER_UNKNOWN":             0,
		"REDISCOVER_OK":                  1,
		"REDISCOVER_FALLBACK":            2,
		"REDISCOVER_ALREADY_IN_PROGRESS": 3,
		"REDISCOVER_FAILED":              4,
	}
)

func (x RediscoverStatus) Enum() *RediscoverStatus {
	p := new(RediscoverStatus)
	*p = x
	return p
}

func (x RediscoverStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RediscoverStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (RediscoverStatus) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x RediscoverStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RediscoverStatus.Descriptor instead.
func (RediscoverStatus) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

type GetTopologyStatus int32

const (
	GetTopologyStatus_TOPOLOGY_OK             GetTopologyStatus = 0
	GetTopologyStatus_TOPOLOGY_NOT_DISCOVERED GetTopologyStatus = 1
)

// Enum value maps for GetTopologyStatus.
var (
	GetTopologyStatus_name = map[int32]string{
		0: "TOPOLOGY_OK",
		1: "TOPOLOGY_NOT_DISCOVERED",
	}
	GetTopologyStatus_value = map[string]int32{
		"TOPOLOGY_OK":             0,
		"TOPOLOGY_NOT_DISCOVERED": 1,
	}
)

func (x GetTopologyStatus) Enum() *GetTopologyStatus {
	p := new(GetTopologyStatus)
	*p = x
	return p
}

func (x GetTopologyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetTopologyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[1].Descriptor()
}

func (GetTopologyStatus) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[1]
}

func (x GetTopologyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetTopologyStatus.Descriptor instead.
func (GetTopologyStatus) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RediscoverTopologyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RediscoverTopologyRequest) Reset() {
	*x = RediscoverTopologyRequest{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RediscoverTopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RediscoverTopologyRequest) ProtoMessage() {}

func (x *RediscoverTopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RediscoverTopologyRequest.ProtoReflect.Descriptor instead.
func (*RediscoverTopologyRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

type RediscoverTopologyResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status RediscoverStatus       `protobuf:"varint,1,opt,name=status,proto3,enum=fabricmanager.agent.RediscoverStatus" json:"status,omitempty"`
	// Human-readable detail: success counts, failure reason, or the reason a
	// rediscovery was rejected.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Present when status is REDISCOVER_OK or REDISCOVER_FALLBACK.
	PhysicalTopology *topology.HostPhysicalTopology `protobuf:"bytes,3,opt,name=physical_topology,json=physicalTopology,proto3" json:"physical_topology,omitempty"`
	// Present when status is REDISCOVER_OK (UMD path); empty on the fallback
	// path because there is no cluster descriptor to serialise.
	ClusterDescriptorYaml string `protobuf:"bytes,4,opt,name=cluster_descriptor_yaml,json=clusterDescriptorYaml,proto3" json:"cluster_descriptor_yaml,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RediscoverTopologyResponse) Reset() {
	*x = RediscoverTopologyResponse{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RediscoverTopologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RediscoverTopologyResponse) ProtoMessage() {}

func (x *RediscoverTopologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RediscoverTopologyResponse.ProtoReflect.Descriptor instead.
func (*RediscoverTopologyResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *RediscoverTopologyResponse) GetStatus() RediscoverStatus {
	if x != nil {
		return x.Status
	}
	return RediscoverStatus_REDISCOVER_UNKNOWN
}

func (x *RediscoverTopologyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RediscoverTopologyResponse) GetPhysicalTopology() *topology.HostPhysicalTopology {
	if x != nil {
		return x.PhysicalTopology
	}
	return nil
}

func (x *RediscoverTopologyResponse) GetClusterDescriptorYaml() string {
	if x != nil {
		return x.ClusterDescriptorYaml
	}
	return ""
}

type GetTopologyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopologyRequest) Reset() {
	*x = GetTopologyRequest{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopologyRequest) ProtoMessage() {}

func (x *GetTopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopologyRequest.ProtoReflect.Descriptor instead.
func (*GetTopologyRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

type GetTopologyResponse struct {
	state                 protoimpl.MessageState         `protogen:"open.v1"`
	Status                GetTopologyStatus              `protobuf:"varint,1,opt,name=status,proto3,enum=fabricmanager.agent.GetTopologyStatus" json:"status,omitempty"`
	PhysicalTopology      *topology.HostPhysicalTopology `protobuf:"bytes,2,opt,name=physical_topology,json=physicalTopology,proto3" json:"physical_topology,omitempty"`
	ClusterDescriptorYaml string                         `protobuf:"bytes,3,opt,name=cluster_descriptor_yaml,json=clusterDescriptorYaml,proto3" json:"cluster_descriptor_yaml,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetTopologyResponse) Reset() {
	*x = GetTopologyResponse{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopologyResponse) ProtoMessage() {}

func (x *GetTopologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopologyResponse.ProtoReflect.Descriptor instead.
func (*GetTopologyResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *GetTopologyResponse) GetStatus() GetTopologyStatus {
	if x != nil {
		return x.Status
	}
	return GetTopologyStatus_TOPOLOGY_OK
}

func (x *GetTopologyResponse) GetPhysicalTopology() *topology.HostPhysicalTopology {
	if x != nil {
		return x.PhysicalTopology
	}
	return nil
}

func (x *GetTopologyResponse) GetClusterDescriptorYaml() string {
	if x != nil {
		return x.ClusterDescriptorYaml
	}
	return ""
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x13fabricmanager.agent\x1a\x0etopology.proto\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x1b\n" +
	"\x19RediscoverTopologyRequest\"\x88\x02\n" +
	"\x1aRediscoverTopologyResponse\x12=\n" +
	"\x06status\x18\x01 \x01(\x0e2%.fabricmanager.agent.RediscoverStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12Y\n" +
	"\x11physical_topology\x18\x03 \x01(\v2,.fabricmanager.topology.HostPhysicalTopologyR\x10physicalTopology\x126\n" +
	"\x17cluster_descriptor_yaml\x18\x04 \x01(\tR\x15clusterDescriptorYaml\"\x14\n" +
	"\x12GetTopologyRequest\"\xe8\x01\n" +
	"\x13GetTopologyResponse\x12>\n" +
	"\x06status\x18\x01 \x01(\x0e2&.fabricmanager.agent.GetTopologyStatusR\x06status\x12Y\n" +
	"\x11physical_topology\x18\x02 \x01(\v2,.fabricmanager.topology.HostPhysicalTopologyR\x10physicalTopology\x126\n" +
	"\x17cluster_descriptor_yaml\x18\x03 \x01(\tR\x15clusterDescriptorYaml*\x91\x01\n" +
	"\x10RediscoverStatus\x12\x16\n" +
	"\x12REDISCOVER_UNKNOWN\x10\x00\x12\x11\n" +
	"\rREDISCOVER_OK\x10\x01\x12\x17\n" +
	"\x13REDISCOVER_FALLBACK\x10\x02\x12\"\n" +
	"\x1eREDISCOVER_ALREADY_IN_PROGRESS\x10\x03\x12\x15\n" +
	"\x11REDISCOVER_FAILED\x10\x04*A\n" +
	"\x11GetTopologyStatus\x12\x0f\n" +
	"\vTOPOLOGY_OK\x10\x00\x12\x1b\n" +
	"\x17TOPOLOGY_NOT_DISCOVERED\x10\x012\xba\x02\n" +
	"\fAgentService\x12M\n" +
	"\x04Ping\x12 .fabricmanager.agent.PingRequest\x1a!.fabricmanager.agent.PingResponse\"\x00\x12w\n" +
	"\x12RediscoverTopology\x12..fabricmanager.agent.RediscoverTopologyRequest\x1a/.fabricmanager.agent.RediscoverTopologyResponse\"\x00\x12b\n" +
	"\vGetTopology\x12'.fabricmanager.agent.GetTopologyRequest\x1a(.fabricmanager.agent.GetTopologyResponse\"\x00b\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_agent_proto_goTypes = []any{
	(RediscoverStatus)(0),                 // 0: fabricmanager.agent.RediscoverStatus
	(GetTopologyStatus)(0),                // 1: fabricmanager.agent.GetTopologyStatus
	(*PingRequest)(nil),                   // 2: fabricmanager.agent.PingRequest
	(*PingResponse)(nil),                  // 3: fabricmanager.agent.PingResponse
	(*RediscoverTopologyRequest)(nil),     // 4: fabricmanager.agent.RediscoverTopologyRequest
	(*RediscoverTopologyResponse)(nil),    // 5: fabricmanager.agent.RediscoverTopologyResponse
	(*GetTopologyRequest)(nil),            // 6: fabricmanager.agent.GetTopologyRequest
	(*GetTopologyResponse)(nil),           // 7: fabricmanager.agent.GetTopologyResponse
	(*topology.HostPhysicalTopology)(nil), // 8: fabricmanager.topology.HostPhysicalTopology
}
var file_agent_proto_depIdxs = []int32{
	0, // 0: fabricmanager.agent.RediscoverTopologyResponse.status:type_name -> fabricmanager.agent.RediscoverStatus
	8, // 1: fabricmanager.agent.RediscoverTopologyResponse.physical_topology:type_name -> fabricmanager.topology.HostPhysicalTopology
	1, // 2: fabricmanager.agent.GetTopologyResponse.status:type_name -> fabricmanager.agent.GetTopologyStatus
	8, // 3: fabricmanager.agent.GetTopologyResponse.physical_topology:type_name -> fabricmanager.topology.HostPhysicalTopology
	2, // 4: fabricmanager.agent.AgentService.Ping:input_type -> fabricmanager.agent.PingRequest
	4, // 5: fabricmanager.agent.AgentService.RediscoverTopology:input_type -> fabricmanager.agent.RediscoverTopologyRequest
	6, // 6: fabricmanager.agent.AgentService.GetTopology:input_type -> fabricmanager.agent.GetTopologyRequest
	3, // 7: fabricmanager.agent.AgentService.Ping:output_type -> fabricmanager.agent.PingResponse
	5, // 8: fabricmanager.agent.AgentService.RediscoverTopology:output_type -> fabricmanager.agent.RediscoverTopologyResponse
	7, // 9: fabricmanager.agent.AgentService.GetTopology:output_type -> fabricmanager.agent.GetTopologyResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
