// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.2
// source: agent.proto

package agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_Ping_FullMethodName               = "/fabricmanager.agent.AgentService/Ping"
	AgentService_RediscoverTopology_FullMethodName = "/fabricmanager.agent.AgentService/RediscoverTopology"
	AgentService_GetTopology_FullMethodName        = "/fabricmanager.agent.AgentService/GetTopology"
	AgentService_RetrainLinks_FullMethodName       = "/fabricmanager.agent.AgentService/RetrainLinks"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService is hosted by each agent (daemon) and exposes actions the
// controller may invoke on the agent. The service shares a port with the
// standard gRPC health checking service registered by the agent process.
//
// This is the service that carries agent-directed control plane actions such
// as triggering local topology rediscovery.
type AgentServiceClient interface {
	// Simple reachability test. The agent echoes back the request's message.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// Re-run local topology discovery and return the fresh state. The call is
	// synchronous: on OK/FALLBACK the response carries the new
	// HostPhysicalTopology and cluster descriptor YAML. The agent serialises
	// rediscoveries and rejects concurrent ones with ALREADY_IN_PROGRESS so
	// that UMD is never invoked from two threads simultaneously.
	RediscoverTopology(ctx context.Context, in *RediscoverTopologyRequest, opts ...grpc.CallOption) (*RediscoverTopologyResponse, error)
	GetTopology(ctx context.Context, in *GetTopologyRequest, opts ...grpc.CallOption) (*GetTopologyResponse, error)
	// Re-train (re-initialise) one or more ethernet links on this host. The
	// agent dispatches each link to the tt-ethtool library, which:
	//   - On Wormhole, writes the SerDes-retrain trigger via the ETH FW
	//     mailbox (ETH_RETRAIN_ADDR). The Blackhole reinit fields on the
	//     per-link request are ignored.
	//   - On Blackhole, sends ETH_MSG_PORT_REINIT_MACPCS with the FW retry
	//     budget and reinit option supplied per-link (defaults are applied
	//     when the fields are zero).
	//
	// The call is synchronous: it returns once every link has been processed.
	// The agent uses two-phase semantics within the batch — it *fires* the
	// reinit/retrain on every link first and only then *waits* for each to
	// complete. This is required by the ETH FW, which only finishes a reinit
	// once the link's peer is also reiniting: the two ends of an intra-host
	// link therefore arrive in one request and must both be kicked off within
	// a few seconds of each other rather than serially. (Cross-host links have
	// their two ends driven by the controller as parallel RPCs to each host.)
	// The response carries one LinkRetrainResult per request entry (in the
	// same order) plus a top-level summary status: OK / PARTIAL / FAILED
	// depending on how many per-link results succeeded.
	RetrainLinks(ctx context.Context, in *RetrainLinksRequest, opts ...grpc.CallOption) (*RetrainLinksResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, AgentService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RediscoverTopology(ctx context.Context, in *RediscoverTopologyRequest, opts ...grpc.CallOption) (*RediscoverTopologyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RediscoverTopologyResponse)
	err := c.cc.Invoke(ctx, AgentService_RediscoverTopology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetTopology(ctx context.Context, in *GetTopologyRequest, opts ...grpc.CallOption) (*GetTopologyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopologyResponse)
	err := c.cc.Invoke(ctx, AgentService_GetTopology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RetrainLinks(ctx context.Context, in *RetrainLinksRequest, opts ...grpc.CallOption) (*RetrainLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrainLinksResponse)
	err := c.cc.Invoke(ctx, AgentService_RetrainLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService is hosted by each agent (daemon) and exposes actions the
// controller may invoke on the agent. The service shares a port with the
// standard gRPC health checking service registered by the agent process.
//
// This is the service that carries agent-directed control plane actions such
// as triggering local topology rediscovery.
type AgentServiceServer interface {
	// Simple reachability test. The agent echoes back the request's message.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// Re-run local topology discovery and return the fresh state. The call is
	// synchronous: on OK/FALLBACK the response carries the new
	// HostPhysicalTopology and cluster descriptor YAML. The agent serialises
	// rediscoveries and rejects concurrent ones with ALREADY_IN_PROGRESS so
	// that UMD is never invoked from two threads simultaneously.
	RediscoverTopology(context.Context, *RediscoverTopologyRequest) (*RediscoverTopologyResponse, error)
	GetTopology(context.Context, *GetTopologyRequest) (*GetTopologyResponse, error)
	// Re-train (re-initialise) one or more ethernet links on this host. The
	// agent dispatches each link to the tt-ethtool library, which:
	//   - On Wormhole, writes the SerDes-retrain trigger via the ETH FW
	//     mailbox (ETH_RETRAIN_ADDR). The Blackhole reinit fields on the
	//     per-link request are ignored.
	//   - On Blackhole, sends ETH_MSG_PORT_REINIT_MACPCS with the FW retry
	//     budget and reinit option supplied per-link (defaults are applied
	//     when the fields are zero).
	//
	// The call is synchronous: it returns once every link has been processed.
	// The agent uses two-phase semantics within the batch — it *fires* the
	// reinit/retrain on every link first and only then *waits* for each to
	// complete. This is required by the ETH FW, which only finishes a reinit
	// once the link's peer is also reiniting: the two ends of an intra-host
	// link therefore arrive in one request and must both be kicked off within
	// a few seconds of each other rather than serially. (Cross-host links have
	// their two ends driven by the controller as parallel RPCs to each host.)
	// The response carries one LinkRetrainResult per request entry (in the
	// same order) plus a top-level summary status: OK / PARTIAL / FAILED
	// depending on how many per-link results succeeded.
	RetrainLinks(context.Context, *RetrainLinksRequest) (*RetrainLinksResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAgentServiceServer) RediscoverTopology(context.Context, *RediscoverTopologyRequest) (*RediscoverTopologyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RediscoverTopology not implemented")
}
func (UnimplementedAgentServiceServer) GetTopology(context.Context, *GetTopologyRequest) (*GetTopologyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopology not implemented")
}
func (UnimplementedAgentServiceServer) RetrainLinks(context.Context, *RetrainLinksRequest) (*RetrainLinksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetrainLinks not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RediscoverTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RediscoverTopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RediscoverTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RediscoverTopology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RediscoverTopology(ctx, req.(*RediscoverTopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetTopology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetTopology(ctx, req.(*GetTopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RetrainLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrainLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RetrainLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RetrainLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RetrainLinks(ctx, req.(*RetrainLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fabricmanager.agent.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _AgentService_Ping_Handler,
		},
		{
			MethodName: "RediscoverTopology",
			Handler:    _AgentService_RediscoverTopology_Handler,
		},
		{
			MethodName: "GetTopology",
			Handler:    _AgentService_GetTopology_Handler,
		},
		{
			MethodName: "RetrainLinks",
			Handler:    _AgentService_RetrainLinks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}
