apiVersion: v2
name: tt-dra-driver
description: Helm chart for the Tenstorrent Dynamic Resource Allocation (DRA) driver

# A chart can be either an 'application' or a 'library' chart.
type: application

# This is the chart version. It is automatically set based on a Git tag when
# a release is published.
version: 0.0.0-dev

# This is the version of the application packaged by this chart. It should
# track the appVersion of the released container image.
appVersion: "v0.0.0-dev"

kubeVersion: ">=1.33.0-0"
